[package]
name = "roc_test_utils"
version = "0.0.1"
authors = ["The Roc Contributors"]
license = "UPL-1.0"
edition = "2021"
description = "Utility functions used all over the code base."

[dependencies]
pretty_assertions = "1.3.0"

# wasm doesn't use directories
[target.'cfg(not(target_family = "wasm"))'.dependencies]
remove_dir_all = "0.7.0"

[dev-dependencies]
