[package]
name = "combined"
version = "0.1.0"
edition = "2018"

[lib]
name = "combined"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
platform = { path = "../platform" }
wasm-bindgen = "0.2.80"
web-sys = { version = "0.3.57", features = [
    'Document',
    'Element',
    'HtmlElement',
    'Node',
    'Window',
]}
app_sys = { path = "../app_sys" }