[package]
name = "host"
version = "0.1.0"
authors = ["The Roc Contributors"]
license = "UPL-1.0"
edition = "2018"
links = "app"

[lib]
name = "host"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "host"
path = "src/main.rs"

[features]
# This feature is only available on Windows platforms
tolk = []

[dependencies]
futures = "0.3"
libc = "0.2"
roc_std = { path = "../../../roc_std" }
tts = "0.20"

[workspace]
