[package]
name = "app_sys"
version = "0.1.0"
edition = "2018"
links = "roc_app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
roc_std = { path = "../../../../roc_std" }

[build-dependencies]
#roc_cli = { path = "../../../../cli" }
