[package]
name = "linker-executable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roc_linker = { path = "../linker" }
tempfile = "3.2.0"
memmap2 = "0.5.7"
indoc = "1.0.7"
libc = "0.2.135"

[target.'cfg(windows)'.dependencies]
memexec = "0.2.0"
