on: [pull_request]

name: Test windows build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  windows-cargo-build:
    name: windows-cargo-build
    runs-on: windows-2022
    timeout-minutes: 90
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
        with:
          clean: "true"

      - name: setup dependencies with nix and build the tests
        run: nix develop -c cargo test --locked --release --no-run